[package]
name = "example_mips64"
version = "0.3.0"
edition = "2021"

[profile.release]
panic = "abort"
debug = true

[dependencies]
# Specifying Martos version
#martos = "0.3.0"
# Specifying current Martos version path for ci
martos = { path = "../../../../" }
cortex-m-rt = "0.6.12"
